export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  ORGANIZER: 'ORGANIZER',
  VOLUNTEER: 'VOLUNTEER',
  ATTENDEE: 'ATTENDEE',
};

export const PERMISSIONS = {
  CREATE_EVENT: 'CREATE_EVENT',
  EDIT_EVENT: 'EDIT_EVENT',
  DELETE_EVENT: 'DELETE_EVENT',
  HOST_HACKATHON: 'HOST_HACKATHON',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  MODERATE_CONTENT: 'MODERATE_CONTENT',
  EDIT_USER: 'EDIT_USER',
  DELETE_USER: 'DELETE_USER',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.DELETE_EVENT,
    PERMISSIONS.HOST_HACKATHON,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.VIEW_ANALYTICS,
    PERMISSIONS.MODERATE_CONTENT,
  ],
  [ROLES.ORGANIZER]: [
    PERMISSIONS.CREATE_EVENT,
    PERMISSIONS.EDIT_EVENT,
    PERMISSIONS.HOST_HACKATHON,
    PERMISSIONS.VIEW_ANALYTICS,
  ],
  [ROLES.VOLUNTEER]: [
    PERMISSIONS.MODERATE_CONTENT,
  ],
  [ROLES.ATTENDEE]: [],
};